
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AplikasiNotaPenjualan extends javax.swing.JFrame {
    String HNasiPecel = "10000";
    String HNasiBaliDaging = "20000";        
    String HNasiCampur = "25000";
    String HEsJeruk = "8000";
    String HEsTehLemon = "10000";
    String HEsCampur = "15000";
    /**
     * Creates new form AplikasiNotaPenjualan
     */
    public AplikasiNotaPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        ComboMakanan = new javax.swing.JComboBox<>();
        lblHarga1 = new javax.swing.JLabel();
        lblHargaMakanan = new javax.swing.JLabel();
        CekMinuman = new javax.swing.JCheckBox();
        ComboMinuman = new javax.swing.JComboBox<>();
        lblHarga2 = new javax.swing.JLabel();
        lblHargaMinuman = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPorsiMakanan = new javax.swing.JLabel();
        lblPorsiMinuman = new javax.swing.JLabel();
        TxtPorsiMakanan = new javax.swing.JTextField();
        TxtPorsiMinuman = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesan Makanan");
        setSize(new java.awt.Dimension(500, 500));

        ComboMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nasi Pecel", "Nasi Bali Daging", "Nasi Campur" }));
        ComboMakanan.setName(""); // NOI18N
        ComboMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMakananActionPerformed(evt);
            }
        });

        lblHarga1.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        lblHarga1.setForeground(new java.awt.Color(255, 51, 0));
        lblHarga1.setText("Harga");

        lblHargaMakanan.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        lblHargaMakanan.setText("0");

        CekMinuman.setFont(new java.awt.Font("Harrington", 1, 12)); // NOI18N
        CekMinuman.setForeground(new java.awt.Color(0, 95, 182));
        CekMinuman.setText("Termasuk dengan minuman ?");
        CekMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekMinumanActionPerformed(evt);
            }
        });

        ComboMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Jeruk", "Es Teh Lemon", "Es Campur" }));
        ComboMinuman.setEnabled(false);
        ComboMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMinumanActionPerformed(evt);
            }
        });

        lblHarga2.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        lblHarga2.setForeground(new java.awt.Color(255, 51, 0));
        lblHarga2.setText("Harga");
        lblHarga2.setEnabled(false);

        lblHargaMinuman.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        lblHargaMinuman.setText("0");
        lblHargaMinuman.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Menu Pesanan");

        lblPorsiMakanan.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        lblPorsiMakanan.setText("Berapa Porsi Makanan ?");

        lblPorsiMinuman.setFont(new java.awt.Font("Ravie", 0, 10)); // NOI18N
        lblPorsiMinuman.setText("Berapa Porsi Minuman ?");
        lblPorsiMinuman.setEnabled(false);

        TxtPorsiMakanan.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        TxtPorsiMakanan.setText("0");

        TxtPorsiMinuman.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        TxtPorsiMinuman.setText("0");
        TxtPorsiMinuman.setEnabled(false);

        btnHitung.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 153, 51));
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        lblTotal.setText("0");

        jLabel1.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        jLabel1.setText("Rp");

        jLabel2.setFont(new java.awt.Font("Mistral", 1, 14)); // NOI18N
        jLabel2.setText("Rp");
        jLabel2.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel3.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHarga1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHarga2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHargaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHargaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addComponent(CekMinuman)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPorsiMakanan)
                                .addComponent(lblPorsiMinuman)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtPorsiMakanan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtPorsiMinuman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga1)
                    .addComponent(lblHargaMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(CekMinuman)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga2)
                    .addComponent(lblHargaMinuman)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorsiMakanan)
                    .addComponent(TxtPorsiMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorsiMinuman)
                    .addComponent(TxtPorsiMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(lblTotal)
                    .addComponent(jLabel3))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMakananActionPerformed

            String msg = (String)ComboMakanan.getSelectedItem();
            switch(msg){
                case "Nasi Pecel":
                    lblHargaMakanan.setText(HNasiPecel);
                    break;
                case "Nasi Bali Daging":
                    lblHargaMakanan.setText(HNasiBaliDaging);
                    break;
                case "Nasi Campur":
                    lblHargaMakanan.setText(HNasiCampur);
                    break;
                default:
                    lblHargaMakanan.setText("0");
                    break;
                    
            }
                    
        
    }//GEN-LAST:event_ComboMakananActionPerformed

    private void CekMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekMinumanActionPerformed
        boolean cek = CekMinuman.isSelected();
        ComboMinuman.setEnabled(cek);
        lblHarga2.setEnabled(cek);
        lblHargaMinuman.setText("0");
        jLabel2.setEnabled(cek);
        lblHargaMinuman.setEnabled(cek);
        lblPorsiMinuman.setEnabled(cek);
        TxtPorsiMinuman.setEnabled(cek);
        TxtPorsiMinuman.setText("0");
        
        
    }//GEN-LAST:event_CekMinumanActionPerformed

    private void ComboMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMinumanActionPerformed
        String msg = (String)ComboMinuman.getSelectedItem();
            switch(msg){
                case "Es Jeruk":
                    lblHargaMinuman.setText(HEsJeruk);
                    break;
                case "Es Teh Lemon":
                    lblHargaMinuman.setText(HEsTehLemon);
                    break;
                case "Es Campur":
                    lblHargaMinuman.setText(HEsCampur);
                    break;
                default:
                    lblHargaMinuman.setText("0");
                    break;
            }
    }//GEN-LAST:event_ComboMinumanActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        Float hargaMakanan = Float.valueOf(lblHargaMakanan.getText());
        Float porsiMakanan = Float.valueOf(TxtPorsiMakanan.getText());
        Float hargaMinuman = Float.valueOf(lblHargaMinuman.getText());
        Float porsiMinuman = Float.valueOf(TxtPorsiMinuman.getText());
        lblTotal.setText(String.valueOf(((hargaMakanan)*(porsiMakanan))+((hargaMinuman)*(porsiMinuman))));
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiNotaPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiNotaPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiNotaPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiNotaPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiNotaPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CekMinuman;
    private javax.swing.JComboBox<String> ComboMakanan;
    private javax.swing.JComboBox<String> ComboMinuman;
    private javax.swing.JTextField TxtPorsiMakanan;
    private javax.swing.JTextField TxtPorsiMinuman;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblHarga1;
    private javax.swing.JLabel lblHarga2;
    private javax.swing.JLabel lblHargaMakanan;
    private javax.swing.JLabel lblHargaMinuman;
    private javax.swing.JLabel lblPorsiMakanan;
    private javax.swing.JLabel lblPorsiMinuman;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
